### ISSUE TITLE
Altitude command on outgoing aircraft stops climb

### ISSUE THREAD

**Issue by mitch-birti-sp** [LesterGallagher/atc-manager-2#1]
Hi, love the game!

I noticed a bug where the climb of an outgoing aircraft is immediately stopped if you give it any altitude commands. For instance:

<img width="160" alt="image" src="https://user-images.githubusercontent.com/43970614/47261006-b2cb2300-d48b-11e8-887d-5c63b9c7bd30.png">
This aircraft took off and began a climb to 13,000ft. Since that would interfere with another aircraft, I issued the following command: "DLT1875 ALT 12000". At that point the aircraft stopped its climb immediately, as shown in the screenshot. It still responds to heading commands, but won't go up or down in altitude.

(Firefox 62.0.3, OSX 10.13.6)

**Comment by LesterGallagher** [comment]
I'm implementing a better than remote logging system, hopefully this is already resolved. Did you set the airplane's "direct to" field to a runway?
